apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: origin-operators
  namespace: origin-marketplace
spec:
  displayName: Aaron's Operators
  image: quay.io/openshift/origin-service-catalog:latest
  publisher: origin
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m