apiVersion: v1
kind: Namespace
metadata:
  name:  origin-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: origin-operators
  namespace: origin-marketplace
spec:
  displayName: Aaron's Operators
  image: quay.io/openshift/origin-service-catalog:latest
  publisher: origin
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m
---
apiVersion: v1
kind: Namespace
metadata:
 name: origin-sriov-network-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: origin-sriov-network-operator
 namespace: origin-sriov-network-operator
spec:
 channel: stable
 name: origin-sriov-network-operator
 source: origin-operators
 sourceNamespace: origin-marketplace
