apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: masters-chrony-configuration
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    networkd: {}
    passwd: {}
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,c2VydmVyIF9nYXRld2F5IGlidXJzdApzZXJ2ZXIgaW5mb2Jsb3gtdHJ1c3QwMS5pbnRyYW5ldC5wcm9kLmludC5waHgyLnJlZGhhdC5jb20gaWJ1cnN0CnNlcnZlciBjbG9jazAxLnV0aWwucGh4Mi5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2suYm9zLnJlZGhhdC5jb20gaWJ1cnN0CnNlcnZlciBjbG9jazEucmR1Mi5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2swMi51dGlsLnBoeDIucmVkaGF0LmNvbSBpYnVyc3QKZHJpZnRmaWxlIC92YXIvbGliL2Nocm9ueS9kcmlmdAptYWtlc3RlcCAxLjAgMwpydGNzeW5jCmxvZ2RpciAvdmFyL2xvZy9jaHJvbnkK
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/chrony.conf
  osImageURL: ""
