kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testpmd
subjects:
- kind: ServiceAccount
  name: testpmd
roleRef:
  kind: Role
  name: testpmd
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trex
subjects:
- kind: ServiceAccount
  name: trex
roleRef:
  kind: Role
  name: trex
  apiGroup: rbac.authorization.k8s.io
