apiVersion: v1
kind: Pod
metadata:
  name: pod-testpmd
#  annotations:
    # k8s.v1.cni.cncf.io/networks: sriov-downlink, sriov-uplink

spec:
  # hostNetwork: true
  # hostPID: true
  # hostIPC: true
  containers:
  - name: samplepod
    command: ["sleep", "99999"]
    image: dockerfranck/testpmd
    securityContext:
        privileged: true
    resources:
      requests:
        openshift.io/intelnics_radio_downlink: "1"
        openshift.io/intelnics_radio_uplink: "1"
        memory: 100Mi
        hugepages-1Gi: 2Gi
        cpu: '1'
      limits:
        openshift.io/intelnics_radio_downlink: "1"
        openshift.io/intelnics_radio_uplink: "1"
        hugepages-1Gi: 2Gi
        cpu: '1'
        memory: 100Mi
    volumeMounts:
      - mountPath: /dev/hugepages
        name: hugepage
        readOnly: False
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
