apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: origin-sriov-network-operator
  namespace: origin-sriov-network-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: origin-sriov-network-operator
  source: origin-operators
  sourceNamespace: origin-marketplace